### ISSUE TITLE
Unable to override any component

### ISSUE THREAD

**Issue by PiotrekFilipecki** [scandipwa/scandipwa#2743]
It's not possible for me to override component as it is shown in tutorial videos. While trying to do so my build crashes with below output:

```
build [==============      ] 69%

{
  filePath: '/Users/piotrekfilipecki/Desktop/etn/src/component/Header/Header.component.js',

  modulePath: '/Users/piotrekfilipecki/Desktop/etn/src/component/Header/Header.component.js',

  packageJson: {}
}
```

As I have discussed it on ScandiPWA slack channel it looks like some eslint errors.

Eslint server crashes as it is visible in Eslint task in vscode terminal

```
[Info  - 8:35:32 PM] ESLint server is starting
[Info  - 8:35:32 PM] ESLint server running in node v14.16.0
[Info  - 8:35:32 PM] ESLint server is running.
[Info  - 8:35:33 PM] ESLint library loaded from: /Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/api.js
{
  filePath: '/Users/piotrekfilipecki/Desktop/etn-app/src/component/Header/Header.component.js',
  modulePath: '/Users/piotrekfilipecki/Desktop/etn-app/src/component/Header/Header.component.js',
  packageJson: {}
}
[Error - 8:36:44 PM] Server process exited with code 1. This usually indicates a misconfigured ESLint setup.
Error: stack
    at process.exit (/Users/piotrekfilipecki/.vscode/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:15282)
    at generateNamespace (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/@scandipwa/eslint-plugin-scandipwa-guidelines/lib/rules/use-namespace.js:179:17)
    at ExportNamedDeclaration > ClassDeclaration,CallExpression[callee.type='MemberExpression'][callee.object.name!=/.+Dispatcher/]:matches([callee.property.name='then'], [callee.property.name='catch']) > ArrowFunctionExpression,ExportNamedDeclaration > VariableDeclaration > VariableDeclarator > ArrowFunctionExpression (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/@scandipwa/eslint-plugin-scandipwa-guidelines/lib/rules/use-namespace.js:228:31)
    at /Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/Users/piotrekfilipecki/Desktop/etn-app/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
[Info  - 8:36:44 PM] Cannot read property 'split' of undefined Occurred while linting /Users/piotrekfilipecki/Desktop/etn-app/src/component/Header/Header.component.js:66
[Error - 8:36:45 PM] Connection to server got closed. Server will not be restarted.
[Info  - 8:36:45 PM] ESLint server stopped.
```

**Comment by carinadues** [comment]
Hey! This issue is fixed in the new versions! :)
