### ISSUE TITLE
ESLint plugin does not work properly in core

### ISSUE THREAD

**Issue by yeegor** [scandipwa/scandipwa#2837]
**Description**:
When all of the ScandiPWA ESLint plugin's rules are switched on in the @scandipwa/scandipwa project and ESLint is ran, the following errors occur.

**Expected behavior**:
ESLint plugin works properly

**Screenshots, Video, Logs**
```bash
TypeError: Cannot read property 'type' of null
Occurred while linting /home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/packages/scandipwa/src/component/MyAccountTabListItem/MyAccountTabListItem.component.js:20
    at /home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/@scandipwa/eslint-plugin-scandipwa-guidelines/lib/util/ast.js:11:22
    at traverse (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/eslint-traverse/index.js:20:18)
    at getIdentifierOccurrences (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/@scandipwa/eslint-plugin-scandipwa-guidelines/lib/util/ast.js:6:5)
    at ClassDeclaration (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/@scandipwa/eslint-plugin-scandipwa-guidelines/lib/rules/derived-class-names.js:32:36)
    at /home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/zhan/Projects/scandipwa/backend242/localmodules/scandipwa/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
```

**Versions**:
- ScandiPWA: 4.4.0
- ESLint: 7.28.0
- @scandipwa/eslint-plugin-scandipwa-guidelines: 2.0.22

**Comment by yeegor** [comment]
Throws at the following files:
MyAccountTableListItem.component.js
ProductCard.component.js
VideoPopup.component.js

**Comment by Elena-Evsa** [comment]
Closing after communication with developer as not actual
