### ISSUE TITLE
Error: Cannot find module 'workbox-webpack-plugin' 

### ISSUE THREAD

**Issue by tim-breitenstein-it** [scandipwa/scandipwa#4218]
**Description**:

1. Upgrade from scandipwa v5.2.0 to v5.2.3
2. `BUILD_MODE=magento npm run start` / `BUILD_MODE=magento npm run build`
3. `Error: Cannot find module 'workbox-webpack-plugin'`

**Expected behavior**:
Working development server / build process

**Screenshots, Video, Logs**

```
08:44 tim@magento2:/var/www/tim/magento-2-4-3/src/localmodules/magento-itb$ BUILD_MODE=magento npm run start

> magento-itb@5.2.3 start
> scandipwa-scripts start

Error: Cannot find module 'workbox-webpack-plugin'
Require stack:
- /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js
- /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@tilework/mosaic-cra-scripts/lib/build-plugins.js
- /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@tilework/mosaic-cra-scripts/lib/craco.js
- /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@tilework/mosaic-cra-scripts/bin/cra-scripts.js
- /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@scandipwa/scandipwa-scripts/bin/scandipwa-scripts.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js',
    '/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@tilework/mosaic-cra-scripts/lib/build-plugins.js',
    '/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@tilework/mosaic-cra-scripts/lib/craco.js',
    '/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@tilework/mosaic-cra-scripts/bin/cra-scripts.js',
    '/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@scandipwa/scandipwa-scripts/bin/scandipwa-scripts.js'
  ]
}


ERROR!

     Failed to load extension`s @scandipwa/service-worker craco-plugins script.
     Looked in /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js file.
     See detailed error log above.
```

**To Reproduce**:
1. Upgrade from scandipwa v5.2.0 to v5.2.3
2. `BUILD_MODE=magento npm run start` / `BUILD_MODE=magento npm run build`
3. See error: `Error: Cannot find module 'workbox-webpack-plugin'`

**Versions**:
- ScandiPWA: v5.2.3
- Magento: v2.4.3
- OS version: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-96-generic x86_64)
- PHP: v7.4.3
- Node: v14.15.4
- npm: v8.3.0
- Composer: v2.1.8

**Comment by AleksandrsKondratjevs** [comment]
Hello!
Have you tried to remove `node_modules` folder and after running `npm install`?

**Comment by tim-breitenstein-it** [comment]
> Hello!
> Have you tried to remove node_modules folder and after running npm install?

Yes of course.

Also installed `workbox-webpack-plugin` manually with new error: 

```
09:10 tim@magento2:/var/www/tim/magento-2-4-3/src/localmodules/magento-itb$ BUILD_MODE=magento npm run start

Starting the development server...

/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

TypeError: Cannot read property 'tapPromise' of undefined
    at /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/workbox-webpack-plugin/build/inject-manifest.js:180:41
    at SyncHook.eval [as call] (eval at create (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/react-scripts/node_modules/webpack/lib/Compiler.js:630:30)
    at /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/react-scripts/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/react-scripts/node_modules/webpack/lib/Compiler.js:662:28)
    at /var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/react-scripts/node_modules/webpack/lib/Watching.js:77:18
    at _next1 (eval at create (/var/www/tim/magento-2-4-3/src/localmodules/magento-itb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
We collect analytics data to make our products more stable and reliable!
If you want to know more go here https://docs.scandipwa.com/about/data-analytics
```

**Comment by AleksandrsKondratjevs** [comment]
Hmm, okey, will check it right now.

**Comment by tim-breitenstein-it** [comment]
ScandiPWA: [v5.2.4](https://github.com/scandipwa/scandipwa/releases/tag/%40scandipwa%2Fscandipwa%405.2.4) does not fix the problem!

**Comment by AleksandrsKondratjevs** [comment]
Release is not related to your issue.

Tried with same versions and kind of no success to reproduce. 
Can you please provide versions for:
```
workbox-webpack-plugin
workbox-build
```

Also good to use npm v6

**Comment by tim-breitenstein-it** [comment]
workbox-webpack-plugin@6.4.2
workbox-build@6.4.2

**Comment by AleksandrsKondratjevs** [comment]
Okey, can you try to install:
```
workbox-webpack-plugin@5.1.4
workbox-build@5.1.4
```

It is set on my clean setup.

**Comment by tim-breitenstein-it** [comment]
> Okey, can you try to install:
> 
> ```
> workbox-webpack-plugin@5.1.4
> workbox-build@5.1.4
> ```
> 
> It is set on my clean setup.

It´s working now.

Deleting the `package-lock.json` and make a clean setup also not work.

**Comment by AleksandrsKondratjevs** [comment]
Hmm, I assume it is because of your versions. 
For sure better to downgrade npm version to v6 and if it is possible, then also use yarn as package manager, it just have bit different package installation flow.

Anyway, if it solves the issues, then we can close issues with your confirmation.
