### ISSUE TITLE
'Magento\Elasticsearch\SearchAdapter\Query\Builder\MatchQuery' not found

### ISSUE THREAD

**Issue by IvanVizcaino** [scandipwa/scandipwa#5024]
**Description**:
What is wrong? What happened?

**Expected behavior**:
When I try to execute php bin:magento setup:di:compile I see the error 'Magento\Elasticsearch\SearchAdapter\Query\Builder\MatchQuery' not found
I can not found this file in vendor magento module.

**Screenshots, Video, Logs**
'''
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 125.0 MiBClass 'Magento\Elasticsearch\SearchAdapter\Query\Builder\MatchQuery' not found#0 /var/www/TheComunity/vendor/composer/ClassLoader.php(478): include()
#1 /var/www/TheComunity/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/TheComunity/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#5 /var/www/TheComunity/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#6 /var/www/TheComunity/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#7 /var/www/TheComunity/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#8 /var/www/TheComunity/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#9 /var/www/TheComunity/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#10 /var/www/TheComunity/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#11 /var/www/TheComunity/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#12 /var/www/TheComunity/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/TheComunity/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#14 /var/www/TheComunity/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#15 /var/www/TheComunity/bin/magento(23): Symfony\Component\Console\Application->run()
#16 {main}
''' 
**To Reproduce**:
1. Upgrade ScandiPWA to 5.3.0 or 5.3.1
2. composer update in magento root directory
3. php bin/magento setup:upgrade
4. php bin/magento setup:di:compile
5. see error

**Versions**:
- ScandiPWA: 5.3.1
- scandipwa/catalog-graphql: 3.2.13
- scandipwa/customer-graph-ql: 4.0.0
- OS version if relevant to the context

**Additional context**:
This required file (Magento\Elasticsearch\SearchAdapter\Query\Builder\MatchQuery) is used in ScandiPWA\CatalogGraphQl\SearchAdapter\Query\Builder\MatchBuilder but not exists in vendor directory

**Comment by IvanVizcaino** [comment]
The error is produced by a bad magento upgrade. Error is solved in magento 2.4.4
