### ISSUE TITLE
Magento2.4.4-p1, redis with password, NOAUTH Authentication required

### ISSUE THREAD

**Issue by suwubee** [scandipwa/scandipwa#5151]
I confirm login redis success.

**Steps to reproduce:**
1. redis with password
2. install magento 2.4.4-p1
3. install scandipwa 5.3.3

**Actual result**
`[2022-08-16T16:54:12.524799+00:00] main.ERROR: NOAUTH Authentication required. [] []
[2022-08-16T16:54:12.524986+00:00] main.CRITICAL: CredisException: NOAUTH Authentication required. in /home/xxx/public_html/vendor/colinmollenhour/credis/Client.php:1306
Stack trace:
#0 /home/xxx/public_html/vendor/colinmollenhour/credis/Client.php(1037): Credis_Client->read_reply()
#1 /home/xxx/public_html/vendor/colinmollenhour/credis/Client.php(658): Credis_Client->__call()
#2 /home/xxx/public_html/vendor/colinmollenhour/credis/Client.php(511): Credis_Client->select()
#3 /home/xxx/public_html/vendor/colinmollenhour/credis/Client.php(814): Credis_Client->connect()
#4 /home/xxx/public_html/vendor/scandipwa/persisted-query/src/RedisClient.php(133): Credis_Client->__call()
#5 /home/xxx/public_html/vendor/scandipwa/persisted-query/src/Plugin/PersistedQuery.php(199): ScandiPWA\PersistedQuery\RedisClient->queryExists()
#6 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): ScandiPWA\PersistedQuery\Plugin\PersistedQuery->processRequest()
#7 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): ScandiPWA\PersistedQuery\Plugin\PersistedQuery\Interceptor->___callParent()
#8 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): ScandiPWA\PersistedQuery\Plugin\PersistedQuery\Interceptor->Magento\Framework\Interception\{closure}()
#9 /home/xxx/public_html/generated/code/ScandiPWA/PersistedQuery/Plugin/PersistedQuery/Interceptor.php(23): ScandiPWA\PersistedQuery\Plugin\PersistedQuery\Interceptor->___callPlugins()
#10 /home/xxx/public_html/vendor/scandipwa/persisted-query/src/Plugin/PersistedQuery.php(186): ScandiPWA\PersistedQuery\Plugin\PersistedQuery\Interceptor->processRequest()
#11 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(135): ScandiPWA\PersistedQuery\Plugin\PersistedQuery->aroundDispatch()
#12 /home/xxx/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}()
#13 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#14 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}()
#15 /home/xxx/public_html/generated/code/Magento/GraphQl/Controller/GraphQl/Interceptor.php(23): Magento\GraphQl\Controller\GraphQl\Interceptor->___callPlugins()
#16 /home/xxx/public_html/vendor/magento/framework/App/Http.php(116): Magento\GraphQl\Controller\GraphQl\Interceptor->dispatch()
#17 /home/xxx/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#18 /home/xxx/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#19 {main} {"report_id":"da9dcf8271e66a0616dca276fd505baf313eac41352fdc8163a7f21cac0f958a"} []`

**Versions**
- ScandiPWA: 5.3.3

**Comment by zans-laksa** [comment]
Did you configure redis in the Magento?
Try to set credentials, using this readme: https://github.com/scandipwa/persisted-query

**Comment by suwubee** [comment]
> Did you configure redis in the Magento? Try to set credentials, using this readme: https://github.com/scandipwa/persisted-query

yes, I config correct, it only success when I leave redis server's  password empty.
