### ISSUE TITLE
we are facing issue with node-gyp,node-sass and python2 in ubuntu os while installing scandipwa?

### ISSUE THREAD

**Issue by magecomp-project** [scandipwa/scandipwa#5425]
we have tried to install existing magento scandipwa theme.we are getting node-sass, node-gyp and phython2 error.

User Guide : https://docs.scandipwa.com/getting-started-1/magento-integration

we have follows steps as per user guide: first we have create existing magento root create src/localmodule directory.

step 1 : mkdir src/localmodule
step 2 : cd src/localmodule

--> after go to src/localmodule this directory and run the below command. we are getting the below error.

Command : npx create-scandipwa-app my-app

I am getting the below errror.

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: html-react-parser@0.13.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from @scandipwa/scandipwa@6.2.1
npm WARN   node_modules/@scandipwa/scandipwa
npm WARN     @scandipwa/scandipwa@"6.2.1" from the root project
npm WARN   11 more (react-redux, react-datepicker, react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14 || ^15 || ^16" from html-react-parser@0.13.0
npm WARN node_modules/html-react-parser
npm WARN   html-react-parser@"^0.13.0" from @scandipwa/scandipwa@6.2.1
npm WARN   node_modules/@scandipwa/scandipwa
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14 || ^15 || ^16" from html-react-parser@0.13.0
npm WARN   node_modules/html-react-parser
npm WARN     html-react-parser@"^0.13.0" from @scandipwa/scandipwa@6.2.1
npm WARN     node_modules/@scandipwa/scandipwa
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-input-range@1.3.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from @scandipwa/scandipwa@6.2.1
npm WARN   node_modules/@scandipwa/scandipwa
npm WARN     @scandipwa/scandipwa@"6.2.1" from the root project
npm WARN   11 more (react-redux, react-datepicker, react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^18.2.0" from react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"18.2.0" from @scandipwa/scandipwa@6.2.1
npm WARN   node_modules/@scandipwa/scandipwa
npm WARN   4 more (react-redux, react-datepicker, @testing-library/react, react-popper)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: stylelint-use-logical@1.1.0
npm WARN Found: stylelint@14.16.1
npm WARN node_modules/stylelint
npm WARN   stylelint@"^14.1.0" from @scandipwa/stylelint-config@0.0.8
npm WARN   node_modules/@scandipwa/stylelint-config
npm WARN     @scandipwa/stylelint-config@"0.0.8" from @scandipwa/scandipwa@6.2.1
npm WARN     node_modules/@scandipwa/scandipwa
npm WARN   4 more (stylelint-config-recommended-scss, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer stylelint@"^9.6.0" from stylelint-use-logical@1.1.0
npm WARN node_modules/stylelint-use-logical
npm WARN   stylelint-use-logical@"^1.1.0" from @scandipwa/stylelint-config@0.0.8
npm WARN   node_modules/@scandipwa/stylelint-config
npm WARN 
npm WARN Conflicting peer dependency: stylelint@9.10.1
npm WARN node_modules/stylelint
npm WARN   peer stylelint@"^9.6.0" from stylelint-use-logical@1.1.0
npm WARN   node_modules/stylelint-use-logical
npm WARN     stylelint-use-logical@"^1.1.0" from @scandipwa/stylelint-config@0.0.8
npm WARN     node_modules/@scandipwa/stylelint-config
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: craco-sass-resources-loader@1.1.0
npm WARN Found: react-scripts@4.0.3
npm WARN node_modules/@tilework/mosaic-cra-scripts/node_modules/react-scripts
npm WARN   react-scripts@"4.0.3" from @tilework/mosaic-cra-scripts@0.1.27
npm WARN   node_modules/@tilework/mosaic-cra-scripts
npm WARN     @tilework/mosaic-cra-scripts@"^0.1.27" from @scandipwa/scandipwa-scripts@2.4.24
npm WARN     node_modules/@scandipwa/scandipwa-scripts
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-scripts@"^2.1.3" from craco-sass-resources-loader@1.1.0
npm WARN node_modules/@tilework/mosaic-cra-scripts/node_modules/craco-sass-resources-loader
npm WARN   craco-sass-resources-loader@"^1.1.0" from @tilework/mosaic-cra-scripts@0.1.27
npm WARN   node_modules/@tilework/mosaic-cra-scripts
npm WARN 
npm WARN Conflicting peer dependency: react-scripts@2.1.8
npm WARN node_modules/react-scripts
npm WARN   peer react-scripts@"^2.1.3" from craco-sass-resources-loader@1.1.0
npm WARN   node_modules/@tilework/mosaic-cra-scripts/node_modules/craco-sass-resources-loader
npm WARN     craco-sass-resources-loader@"^1.1.0" from @tilework/mosaic-cra-scripts@0.1.27
npm WARN     node_modules/@tilework/mosaic-cra-scripts
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated rollup-plugin-terser@5.3.1: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated mini-create-react-context@0.4.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js-pure@3.8.0: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
npm ERR! code 1
npm ERR! path /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@19.9.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb `which` succeeded python2.7 /usr/bin/python2.7
npm ERR! gyp verb check python version `/usr/bin/python2.7 -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 19.9.0
npm ERR! gyp verb command install [ '19.9.0' ]
npm ERR! gyp verb install input version string "19.9.0"
npm ERR! gyp verb install installing version: 19.9.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 19.9.0
npm ERR! gyp verb build dir attempting to create "build" dir: /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python2.7
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.node-gyp/19.9.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/19.9.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/19.9.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
npm ERR!     params['parallel'], params['root_targets'])
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
npm ERR!     variables, includes, depth, check, True)
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
npm ERR!     includes, True, check)
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
npm ERR!     aux_data, includes, check)
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
npm ERR!     LoadOneBuildFile(include, data, aux_data, None, False, check),
npm ERR!   File "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
npm ERR!     None)
npm ERR!   File "/root/.node-gyp/19.9.0/include/node/common.gypi", line 1
npm ERR!     nerate ',
npm ERR!             ^
npm ERR! SyntaxError: EOL while scanning string literal
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.15.0-69-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/var/www/html/demo245/src/localmodules/my-app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /var/www/html/demo245/src/localmodules/my-app/node_modules/node-sass
npm ERR! gyp ERR! node -v v19.9.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-04-14T11_00_56_507Z-debug-0.log
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.9.0
```

please help me what we need to do next to solve this issue!!!!!

**Comment by AleksandrsKondratjevs** [comment]
Hello!
Be sure that you running on node 14 version

**Comment by team-mavengers** [comment]
> Hello! Be sure that you running on node 14 version

yes, it's working on node 14 version., thank you so much for helping us...
i am getting one more issue, one installation complete after trying to run magento upgrade command i am getting the `Call to undefined method Laminas\Validator\NotEmpty::setDisableTranslator()` error.

**Comment by AleksandrsKondratjevs** [comment]
@team-mavengers whats version magento and scandipwa trying to install?

**Comment by team-mavengers** [comment]
@AleksandrsKondratjevs currently i am trying to install scandipwa theme in Magento 2.4.6 version

**Comment by team-mavengers** [comment]
@AleksandrsKondratjevs Thank you so much, i have done setup in my local server.
https://i.imgur.com/Zno2jk9.png

**Comment by VikasTiwari-Webkul** [comment]
@team-mavengers did you find any solution?

**Comment by AleksandrsKondratjevs** [comment]
@team-mavengers hey! can you please output @scandipwa package versions you have by composer installed?
